# Generated by Django 3.2.9 on 2021-12-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='selfintroduce',
            field=models.TextField(blank=True),
        ),
    ]
