# Generated by Django 3.2.9 on 2021-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('isMale', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
