# Generated by Django 3.2.9 on 2021-11-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_expert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expert',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
