# Generated by Django 3.2.9 on 2021-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField(default='D:\\下载目录\\aminer_papers_0.txt')),
                ('pointer', models.IntegerField(default=0)),
            ],
        ),
    ]
