# Generated by Django 3.2.9 on 2021-11-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='unknow', max_length=64)),
                ('DocID', models.CharField(max_length=64, null=True)),
                ('nextAuthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.author')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, null=True, unique=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pattern.user')),
                ('realName', models.CharField(max_length=64)),
            ],
            bases=('pattern.user',),
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pattern.user')),
                ('mecName', models.CharField(max_length=128)),
                ('briefIntro', models.TextField(null=True)),
                ('ranking', models.IntegerField(null=True)),
            ],
            bases=('pattern.user',),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocID', models.CharField(max_length=64, null=True)),
                ('key', models.CharField(max_length=64)),
                ('nextKey', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DOI', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('DocID', models.CharField(max_length=32, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('mainBody', models.FileField(null=True, upload_to='')),
                ('pubYear', models.IntegerField(default=1900)),
                ('citation', models.IntegerField(default=0)),
                ('firstAuthor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.author')),
                ('firstKeyword', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('nextComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecName', models.CharField(max_length=128)),
                ('operatorID', models.CharField(max_length=32)),
                ('certificateFile', models.FileField(upload_to='')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pattern.user')),
                ('EID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=64)),
                ('realName', models.CharField(max_length=128)),
                ('pubNum', models.IntegerField(null=True)),
                ('isCertified', models.BooleanField(default=False)),
                ('mec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.mechanism')),
            ],
            bases=('pattern.user',),
        ),
    ]
