# Generated by Django 3.2.9 on 2021-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_auto_20211116_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neckname', models.CharField(max_length=64)),
                ('dataTime', models.DateTimeField()),
                ('DOI', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.IntegerField(default=0),
        ),
    ]
