# Generated by Django 3.2.9 on 2021-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_alter_readinghead_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinghead',
            name='fileName',
            field=models.TextField(default='D:\\下载目录\\aminer_papers_0.txt'),
        ),
    ]
